version: '3.8'

name: python_swarm
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == worker

